# Generated by Django 5.1.1 on 2024-11-24 11:40
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="category",
            field=models.CharField(
                choices=[
                    ("GA", "gaming"),
                    ("SO", "software"),
                    ("SC", "source code"),
                    ("WR", "writing"),
                    ("AI", "Artifical Intelligence"),
                    ("MI", "Miscellaneous"),
                    ("HE", "Help"),
                ],
                default="SO",
                max_length=2,
            ),
        ),
    ]
