# Generated by Django 5.1.1 on 2024-10-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="snippet",
            name="view_once",
            field=models.BooleanField(default=False),
        ),
    ]
