# Generated by Django 5.1.1 on 2024-10-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_onetimecode_snippet_view_once"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="snippet_expiration",
            field=models.DateTimeField(null=True),
        ),
    ]
