# Generated by Django 5.1.1 on 2024-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_snippet_snippet_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="snippet_expiration",
            field=models.CharField(
                choices=[
                    ("NO", "never"),
                    ("10", "10 minutes"),
                    ("1H", "one hour"),
                    ("1D", "one day"),
                    ("1W", "one week"),
                    ("1M", "one month"),
                ],
                default="NO",
                max_length=2,
            ),
        ),
    ]
