# Generated by Django 5.1.1 on 2024-10-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_snippet_snippet_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="snippet_expired_date",
            field=models.DateTimeField(null=True),
        ),
    ]
