# Generated by Django 5.1.1 on 2024-11-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_snippet_snippet_expired_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="password",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
