# Generated by Django 5.1.1 on 2024-11-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_snippet_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_token", models.UUIDField()),
            ],
        ),
    ]
