# Generated by Django 5.1.1 on 2024-11-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_passwordtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordtoken",
            name="password_token",
            field=models.CharField(max_length=36),
        ),
    ]
